---
- name: Déployer Grafana
  hosts: monitoring
  become: yes
  vars_files:
    - vars/global.yml
  tasks:
    - name: Installer les dépendances
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - gnupg
          - ca-certificates
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Ajouter le dépôt
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Mettre à jour APT
      apt:
        update_cache: yes

    - name: Installer Grafana
      apt:
        name: grafana
        state: present

    - name: Copier la configuration
      template:
        src: templates/grafana.ini.j2
        dest: /etc/grafana/grafana.ini
        mode: "0644"
      notify: Restart Grafana

    - name: S’assurer que Grafana est démarré
      systemd:
        name: grafana-server
        state: started
        enabled: yes

  handlers:
    - name: Restart Grafana
      systemd:
        name: grafana-server
        state: restarted
        enabled: yes
